version: 1
disable_existing_loggers: false
formatters:
  user:
    format: '[%(asctime)s] %(name)s {%(pathname)s@%(funcName)s:%(lineno)d} %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'
  simple:
    format: "[%(asctime)s] %(name)s {%(pathname)s@%(funcName)s:%(lineno)d} %(levelname)s - %(message)s"
    datefmt: '%m/%d/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler # sends logging output to streams such as sys.stdout, sys.stderr
    level: DEBUG
    formatter: user
    stream: 'ext://sys.stdout'
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'src/logs/logs.log'
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  file_for_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: src/logs/errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  file_for_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: src/logs/debugs.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  file_for_root:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: src/logs/root.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  production:
    level: INFO
    handlers:
      - file
      - file_for_error
      - file_for_root
    propagate: no
  develop:
    level: DEBUG
    handlers:
      - file
      - file_for_error
      - file_for_debug
      - file_for_root
    propagate: no
  console:
    level: DEBUG
    handlers:
      - console
    propagate: no
root: # root logger
  level: DEBUG
  handlers:
    - file_for_root