version: '3'
services:
  python3:
    restart: always
    build: ./infra/python/
    container_name: 'new_tracks'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./backend/:/root
    environment:
      SPOTIPY_CLIENT_ID: ${SPOTIPY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${SPOTIPY_CLIENT_SECRET}