from configparser import ConfigParser

# Set up config as dict
config_file = 'config.ini'
CONFIG = ConfigParser()
CONFIG.read(config_file)

FILE_PATH_OF_BOOKMARKS                   = CONFIG['FILES']['DIR'] + CONFIG['FILES']['FILENAME_OF_BOOKMARKS'] 
FILE_PATH_OF_OWN_EXAMPLES                = CONFIG['FILES']['DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_EXAMPLES'] 
FILE_PATH_OF_OWN_DEFINITIONS             = CONFIG['FILES']['DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_DEFINITION'] 
FILE_PATH_OF_CSV                         = CONFIG['FILES']['DIR'] + CONFIG['FILES']['FILENAME_OF_CSV'] 
FILE_PATH_OF_VOCABULARIES_TO_SCRAPE      = CONFIG['FILES']['DIR'] + CONFIG['FILES']['FILENAME_OF_VOCABULARY_TO_SCRAPE'] 
FILE_PATH_OF_VOCABULARIES_SCRAPED        = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_VOCABULARY_SCRAPED'] 
FILE_PATH_OF_VOCABULARIES_NOT_SCRAPED    = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_VOCABULARY_NOT_SCRAPED'] 
FILE_PATH_OF_VOCABULARIES_WRITTEN        = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_VOCABULARY_WRITTEN'] 
FILE_PATH_OF_VOCABULARIES_EXISTED        = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_VOCABULARY_EXISTED'] 
FILE_PATH_OF_OWN_EXAMPLES_WRITTEN        = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_EXAMPLE_WRITTEN'] 
FILE_PATH_OF_OWN_EXAMPLES_NOT_WRITTEN    = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_EXAMPLE_NOT_WRITTEN']
FILE_PATH_OF_OWN_DEFINITIONS_WRITTEN     = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_DEFINITION_WRITTEN'] 
FILE_PATH_OF_OWN_DEFINITIONS_NOT_WRITTEN = CONFIG['FILES']['DIR'] + CONFIG['FILES']['RESULT_DIR'] + CONFIG['FILES']['FILENAME_OF_OWN_DEFINITION_NOT_WRITTEN'] 

FILES_TO_BE_CHECKED = [
    FILE_PATH_OF_OWN_EXAMPLES,
    FILE_PATH_OF_OWN_DEFINITIONS, 
    FILE_PATH_OF_CSV,
    FILE_PATH_OF_VOCABULARIES_TO_SCRAPE,
    FILE_PATH_OF_VOCABULARIES_SCRAPED,
    FILE_PATH_OF_VOCABULARIES_NOT_SCRAPED,
    FILE_PATH_OF_VOCABULARIES_WRITTEN,
    FILE_PATH_OF_VOCABULARIES_EXISTED,
    FILE_PATH_OF_OWN_EXAMPLES_WRITTEN,
    FILE_PATH_OF_OWN_EXAMPLES_NOT_WRITTEN,
    FILE_PATH_OF_OWN_DEFINITIONS_WRITTEN,
    FILE_PATH_OF_OWN_DEFINITIONS_NOT_WRITTEN]

FILES_TO_BE_DELETE = [
    FILE_PATH_OF_BOOKMARKS, 
    FILE_PATH_OF_OWN_EXAMPLES,
    FILE_PATH_OF_OWN_DEFINITIONS,
    FILE_PATH_OF_CSV,
    FILE_PATH_OF_VOCABULARIES_TO_SCRAPE]

DIR = CONFIG['FILES']['DIR']