from configparser import ConfigParser

# Set up config as dict
config_file = 'config.ini'
CONFIG = ConfigParser()
CONFIG.read(config_file)


FILE_PATH_OF_CSV = CONFIG['FILES']['DIR_CSV'] + CONFIG['FILES']['FILENAME_OF_CSV'] + CONFIG['FILES']['EXTENSION_OF_CSV']
FILE_PATH_OF_CSV = CONFIG['FILES']['DIR_CSV'] + CONFIG['FILES']['FILENAME_OF_CSV'] + CONFIG['FILES']['EXTENSION_OF_CSV']

PLAYLIST_ID_JP = CONFIG['PLAYLIST_ID']['JP']
PLAYLIST_ID_PH = CONFIG['PLAYLIST_ID']['PH']

PLAYLIST_IDS = [
    {'country': 'JP': 'id': PLAYLIST_ID_JP},
    {'country': 'PH': 'id': PLAYLIST_ID_PH}
]

# FILES_TO_BE_CHECKED = [
#     FILE_PATH_OF_OWN_EXAMPLES,
#     FILE_PATH_OF_OWN_DEFINITIONS, 
#     FILE_PATH_OF_CSV,
#     FILE_PATH_OF_VOCABULARIES_TO_SCRAPE,
#     FILE_PATH_OF_VOCABULARIES_SCRAPED,
#     FILE_PATH_OF_VOCABULARIES_NOT_SCRAPED,
#     FILE_PATH_OF_VOCABULARIES_WRITTEN,
#     FILE_PATH_OF_VOCABULARIES_EXISTED,
#     FILE_PATH_OF_OWN_EXAMPLES_WRITTEN,
#     FILE_PATH_OF_OWN_EXAMPLES_NOT_WRITTEN,
#     FILE_PATH_OF_OWN_DEFINITIONS_WRITTEN,
#     FILE_PATH_OF_OWN_DEFINITIONS_NOT_WRITTEN]

# FILES_TO_BE_DELETE = [
#     FILE_PATH_OF_BOOKMARKS, 
#     FILE_PATH_OF_OWN_EXAMPLES,
#     FILE_PATH_OF_OWN_DEFINITIONS,
#     FILE_PATH_OF_CSV,
#     FILE_PATH_OF_VOCABULARIES_TO_SCRAPE]

# DIR = CONFIG['FILES']['DIR']